version: '2'
services:
#  proxy:
#    image: wildcat/scylla
#    ports:
#      - 8899:8899
#      - 8081:8081
#    volumes:
#      - ./volumes/scylla:/var/www/scylla
  db:
    image: docker.io/influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: duApp
  ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./volumes/grafana:/var/lib/grafana

